---
name: Word Warden
author: Simon Bengtsson
description: Spellcheck your text files
inputs:
  files:
    description: "Files to spellcheck, (glob expressions accepted)."
    required: false
    default: "**/*.md"
  language:
    description: |
      "Language of your text files, specified as a locale code
      (in format accepted by aspell, such as en_US)."
    required: false
    default: "en_US"
  dictionary:
    description: "Path to your personal dictionary in aspell format."
    required: false
  word_warden_ref:
    description: "Version of Word Warden to checkout (only for development)."
    default: "v0.2.0"
    required: false
runs:
  using: composite
  steps:

    - name: Checkout repository to spellcheck
      uses: actions/checkout@v4
      with:
        path: evaluated-repository

    - name: Checkout Word Warden
      uses: actions/checkout@v4
      with:
        repository: gevhaz/word-warden
        ref: ${{ inputs.word_warden_ref }}
        path: word-warden

    - name: Extract spelling language code
      run: |
        # Extract spelling language code
        INPUT_LOCALE=${{ inputs.language }}
        echo "SPELLLANG=${INPUT_LOCALE:0:2}" >> $GITHUB_ENV
      shell: bash

    - name: Install apt prerequisites
      run: |
        echo "::group::Install apt prerequisites"
        sudo apt update
        sudo apt install -y -qq aspell pandoc python3-pip aspell-$SPELLLANG
        echo "::endgroup::"
      shell: bash

    - name: Install Python prerequisites
      run: |
        echo "::group::Install Python prerequisites"
        pip install beautifulsoup4
        echo "::endgroup::"
      shell: bash

    - name: Create empty dictionary if none is provided
      run: |
        # Create empty dictionary if none is provided
        if [ -z "${{ inputs.dictionary }}" ]; then
          DEFAULT_DICTIONARY=.github/data/project-dictionary.txt
          if [ ! -f "$DEFAULT_DICTIONARY" ]; then
            mkdir -p .github/data
            echo "personal_ws-1.1 en 12 utf-8" > "$DEFAULT_DICTIONARY"
          fi
          echo "DICTIONARY_PATH=$DEFAULT_DICTIONARY" >> $GITHUB_ENV
        else
          echo "DICTIONARY_PATH=${{ inputs.dictionary }}" >> $GITHUB_ENV
        fi
      shell: bash
      working-directory: evaluated-repository

    - name: Spellcheck files
      run: |
        # SPELLCHECK FILES
        # Expand globbing expression
        shopt -s globstar extglob
        IFS=$'\n'
        FILES=()
        for file in ${{ inputs.files }}; do
          FILES+=("$file")
        done
        unset IFS

        # Do the spellchecking
        python3 ../word-warden/spellcheck.py \
          --dictionary="$DICTIONARY_PATH" \
          --language="${{ inputs.language }}" \
          "${FILES[@]}"
      shell: bash
      working-directory: evaluated-repository
