---
name: Code quality

on:
  pull_request:
    branches: [main]

jobs:

  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          - "flake8"
          - "mypy --strict"
          - "black --check --diff --color"
          - "isort --check -diff"

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r dev-requirements.txt

      - name: Run check
        run: ${{ matrix.tool }} .
